import { StyleSheet } from '@react-pdf/renderer'

export const styles = StyleSheet.create({
  cls_002: {
    fontSize: '16.1px',
    color: 'rgb(0,0,0)',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  cls_003: {
    fontSize: '10.1px',
    color: 'rgb(0,0,0)',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  cls_004: {
    fontSize: '10.1px',
    color: 'rgb(0,0,0)',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  cls_005: {
    fontSize: '10.1px',
    color: 'rgb(255,255,255)',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  cls_006: {
    fontSize: '9.8px',
    color: 'rgb(0,0,0)',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  cls_007: {
    fontSize: '11.0px',
    color: 'rgb(0,0,0)',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  cls_009: {
    fontSize: '5.0px',
    color: 'rgb(0,0,0)',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  cls_010: {
    fontSize: '5.0px',
    color: 'rgb(0,0,0)',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  cls_011: {
    fontSize: '6.0px',
    color: 'rgb(0,0,0)',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'none',
  },
  cls_012: {
    fontSize: '6.0px',
    color: 'rgb(0,0,0)',
    fontWeight: 'bold',
    fontStyle: 'normal',
    textDecoration: 'underline',
  },

  darkBackground: {
    backgroundColor: '#242424',
    width: '38%',
    height: '14px',
    lineHeight: '8px',
  },

  table: {
    fontSize: 10,
    width: 550,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignContent: 'stretch',
    flexWrap: 'nowrap',
    alignItems: 'stretch',
  },
  tableRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignContent: 'stretch',
    flexWrap: 'nowrap',
    alignItems: 'stretch',
    flexGrow: 0,
    flexShrink: 0,
  },
  cell: {
    borderColor: '#ededed',
    borderStyle: 'solid',
    borderWidth: 1,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 'auto',
    alignSelf: 'stretch',
  },
  textCenter: {
    textAlign: 'center',
  },
  textLeft: {
    textAlign: 'left',
  },
  textRight: {
    textAlign: 'right',
  },
})
