import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({

  cls_002: {
    fontFamily: "Times,serif",
    fontSize: "16.1px",
    color: "rgb(0,0,0)",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
  },
  cls_003: {
    fontFamily: "Times,serif",
    fontSize: "10.1px",
    color: "rgb(0,0,0)",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
  },
  cls_004: {
    fontFamily: "Times,serif",
    fontSize: "10.1px",
    color: "rgb(0,0,0)",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
  },
  cls_005: {
    fontFamily: "Times,serif",
    fontSize: "10.1px",
    color: "rgb(255,255,255)",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
  },
  cls_006: {
    fontFamily: "Times,serif",
    fontSize: "9.8px",
    color: "rgb(0,0,0)",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
  },
  cls_007: {
    fontFamily: "Times,serif",
    fontSize: "11.0px",
    color: "rgb(0,0,0)",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
  },
  cls_009: {
    fontFamily: "Arial,serif",
    fontSize: "5.0px",
    color: "rgb(0,0,0)",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
  },
  cls_010: {
    fontFamily: "Arial,serif",
    fontSize: "5.0px",
    color: "rgb(0,0,0)",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
  },
  cls_011: {
    fontFamily: "Arial,serif",
    fontSize: "6.0px",
    color: "rgb(0,0,0)",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
  },
  cls_012: {
    fontFamily: "Arial,serif",
    fontSize: "6.0px",
    color: "rgb(0,0,0)",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "underline",
  },
});
