export const PURCHASE_REQUISITION_APPROVAL_TITLE_HEIGHT: number = 40;
export const PURCHASE_REQUISITION_APPROVAL_TOP_TOOLS_HEIGHT: number = 110;
export const PURCHASE_REQUISITION_APPROVAL_BOTTOM_TOOLS_HEIGHT: number = 90;
export const PURCHASE_REQUISITION_APPROVAL_TABLE_SEARCHBAR_HEIGHT: number = 35;
export const PURCHASE_REQUISITION_APPROVAL_TABLE_HEADER_HEIGHT: number = 66;
