export const PURCHASE_ORDER_RECEIPT_TABLE_HEADER_HEIGHT: number = 65;
export const PURCHASE_ORDER_RECEIPT_TITLE_HEIGHT: number = 40;
export const PURCHASE_ORDER_RECEIPT_TOP_TOOLS_HEIGHT: number = 60;
