export const PURCHASE_REQUISITION_SUBMISSION_TOP_TOOLS_HEIGHT: number = 120;
export const PURCHASE_REQUISITION_SUBMISSION_TABLE_SEARCHBAR_HEIGHT: number = 35;
export const PURCHASE_REQUISITION_SUBMISSION_REMARKS_HEIGHT: number = 70;
