export const PURCHASE_ORDER_RECEIPT_CREATION_TITLE_HEIGHT: number = 40;
export const PURCHASE_ORDER_RECEIPT_CREATION_TOP_TOOLS_HEIGHT: number = 60;
export const PURCHASE_ORDER_RECEIPT_CREATION_BOTTOM_TOOLS_HEIGHT: number = 80;
